### PR TITLE
Add delegation support to subnet

### LINKED ISSUE #46: Enable adding delegation for azurerm_subnet
A delegation block supports the following:

    name (Required) A name for this delegation.

    service_delegation (Required) A service_delegation block as defined below.

### PR DESCRIPTION
**Pull request by stanleyz**
Fixes #46  

Changes proposed in the pull request:

1. Adding delegation support to subnet

### CODE REVIEW

**Comment by dumblerod** [comment]
How can we get this update merged in? I've tested this in my own environment and it works great!

**Comment by stanleyz** [comment]
The repo seems pretty dead to me, it has been no update for months.

**Review by dumblerod — APPROVED** [review]
Tested changes and seems to be working as expected.

**Comment by klesperance** [comment]
Would like to see this merged in as well

**Review by lonegunmanb — COMMENTED** [review]
LGTM!

**Review by lonegunmanb — APPROVED** [review]

**Pull request merged**
