### PR TITLE
Added new output "vnet_subnets_name_id"

### PR DESCRIPTION
**Pull request by vinshetty**
Can be query subnet id by subnet name this will help to refer in subsequent resource creation where it requires subnet ID, For example, need subnet ID to Application Gateway
  Here is the example 
locals {
  frontend_subnet_id             = lookup(module.vnet.vnet_subnets_name_id, subnet1)
} 
The current output "vnet_subnets"  it not user friendly which i feel

Fixes #000 

Changes proposed in the pull request:

### CODE REVIEW

**Comment by jiaweitao001** [comment]
Hi @vinshetty, this change LGTM. Can you please rebase it? Thanks.

**Review by jiaweitao001 — APPROVED** [review]

**Comment by vinshetty** [comment]
Hi @jiaweitao001 , Thanks for approving the changes

**Comment by holms** [comment]
@jiaweitao001 maybe this could be merged already? Whole year passed. Is this module even maintained? Or it's not official azure vpc terraform module?

**Comment by lonegunmanb** [comment]
@holms Sorry for the crazy late reply, we're going to re-active this module this week. We'll add a new CI pipeline to this module first, once the pipeline works, we'll review and merge this pr. I promise this feature will be merged in next week.

**Pull request merged**
